### ISSUE TITLE
Does not automatically include the LoopBack module in app.js

### ISSUE THREAD

**Issue by TreyOverton** [DigitalMachinist/loopback-angular-ui-router#1]
When I added my first model to be accessed from the app, I was getting errors when trying to use that model in a controller in the client. Adding 'LoopBack' as a module requirement fixed it. Maybe this is totally obvious to people, but as someone relatively new to Angular, Node, and LoopBack, it threw me for a couple hours. Maybe it would be appropriate to automatically include it? Like so?

angular
  .module( 'yourApp', [
    'ngResource',
    'ui.router',
    'LoopBack'
  ] )
  .config...

**Comment by DigitalMachinist** [comment]
@AaronOverton

This will seem tremendously overdue, but somehow I just became aware that people are actually using this project, so I'm going to do a little bit of work to bring it up to speed and check for some of these problems.

I'm still at work right now so I can't test this currently, but I'll get home, clone this and try to replicate. What you're saying makes plenty of sense to me, though, so I'll likely implement this change.

Also, thank you for your lovely PR to the grunt process. It was a huge gruntfile, so I really appreciate you splitting it up into more manageable bits.

**Comment by TreyOverton** [comment]
The PR wasn't me, so I can't accept your thanks on that one. :)

Also, I've generally been a Subversion user for years. I could have made the change and submitted a pull request, but at the time I emailed you, I was still pretty Git-clueless. The last few months have been a time of huge learning to the point where I am somehow an admin for a large client's private GitHub set of repos. Whoa.

So if you want me to do a pull request, I could do that now, or you can just take care of it this time per my suggestion.

The StrongLoop guys are presenting this repo as a good example, I think, so I bet there might be a surprising number of people using it for learning and reference!

**Comment by dev-augmenta** [comment]
Absolutely true. And it's the only package that gives both a good loopback + angular + tests scaffold. If we get the /api entrypoint and /explorer back on track this will be epic :)

**Comment by DigitalMachinist** [comment]
@AaronOverton 

Oops! I'm not sure how I got that mixed up, but nonetheless thanks for bringing this issue to light. I'm finally sitting down to work on this so I'll see about including it momentarily.

> The StrongLoop guys are presenting this repo as a good example, I think, so I bet there might be a surprising number of people using it for learning and reference!

wat

I really wouldn't have guessed anything like that. Maybe I'll hear from someone on the StrongLoop team sometime.

**Comment by TreyOverton** [comment]
I suspect you won't, now that they have been purchased by IBM. :)

**Comment by DigitalMachinist** [comment]
@AaronOverton 

I heard about that, although I'm not really up on the organizational flux they might be undergoing. Not sure if they're still operating at arm's length as the StrongLoop team or if they've been shaken up since the acquisition.

**Comment by DigitalMachinist** [comment]
I'm going to call this closed since there aren't really any symptoms to test in the wake of a potential fix.

Thanks for pointing this out!
