### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by JefferE** [DigitalMachinist/loopback-angular-ui-router#2]
I'm trying to use this project and am getting errors during grunt testing regarding gitWritingApp despite the commit logs saying that module has been removed:

Errors:

INFO [karma]: Karma v0.12.37 server started at http://localhost:8080/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 45.0.2454 (Windows 7 0.0.0)]: Connected on socket aFZm5L8SP6nAcwUyItMJ with id 18391702
Chrome 45.0.2454 (Windows 7 0.0.0) Module: gitWritingApp Controller: MainCtrl should attach a list of awesomeThings to the scope FAILED
        Error: [$injector:modulerr] Failed to instantiate module gitWritingApp due to:
        Error: [$injector:nomod] Module 'gitWritingApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
        http://errors.angularjs.org/1.4.6/$injector/nomod?p0=gitWritingApp
            at E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:68:12
            at E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:1986:17
            at ensure (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:1910:38)
            at module (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:1984:14)
            at E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:4388:22
            at forEach (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:336:20)
            at loadModules (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:4372:5)
            at Object.createInjector [as injector](E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:4297:11)
            at Object.workFn (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular-mocks/angular-mocks.js:2427:52)
        http://errors.angularjs.org/1.4.6/$injector/modulerr?p0=gitWritingApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'gitWritingApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.6%2F%24injector%2Fnomod%3Fp0%3DgitWritingApp%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A1986%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A1910%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A1984%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A4388%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A336%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A4372%3A5)%0A%20%20%20%20at%20Object.createInjector%20%5Bas%20injector%5D%20(http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3Fe9c46e66ca534bf6008860176d93bae434687fb7%3A4297%3A11)%0A%20%20%20%20at%20Object.workFn%20(http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fapp%2Fbower_components%2Fangular-mocks%2Fangular-mocks.js%3Fa6f60920a9e460d21052862d777b6f079abcf5a0%3A2427%3A52)%0A%20%20%20%20at%20attemptSync%20(http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1789%3A24)
            at E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:68:12
            at forEach (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:336:20)
            at loadModules (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:4372:5)
            at Object.createInjector [as injector](E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:4297:11)
            at Object.workFn (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular-mocks/angular-mocks.js:2427:52)
            at E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/app/bower_components/angular/angular.js:4411:15
        TypeError: Cannot read property 'awesomeThings' of undefined
            at Object.<anonymous> (E:/Dvlp/AngularJS/loopback-angular-ui-router/loopback-angular-ui-router/test/spec/controllers/main.js:20:20)
Chrome 45.0.2454 (Windows 7 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.034 secs / 0.029 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.

**Comment by dev-augmenta** [comment]
I hadthe same issue:

just replace 'gitWritingApp' with 'yourApp'  where 'yourApp' has to be equal to the name of the angular module name you put in /app/scripts/app.js

**Comment by DigitalMachinist** [comment]
Thanks @dev-augmenta for providing the fix.
I should go through and make that entry in the Karma config clearer so no one mistakes that.

This is my first indication that anyone is trying to use or cares about this project. I haven't maintained it for a little while, but is there anything that desperately needs to be changed/added? I should probably do a quick pass over it to make sure everything's working as it should be.

**Comment by dev-augmenta** [comment]
Hi, I think it's a great project! I'm very new to node, express, loopback and angular world. Now I've basic knowledge of loopback and your project is saving me a lot of time and helping me understand.
Actually I've a new issue when I try to add more models. Grunt fail when invoking the loopback-angular generator. I'll post a new issue for you

**Comment by DigitalMachinist** [comment]
Thanks again @dev-augmenta for the fix. The latest build has incorporated this and it seems to take care of this issue. I'm closing this for now, but please submit a fresh issue report if this persists under future versions and I'll re-open it.
