### ISSUE TITLE
Warning: Task "serve" not found.

### ISSUE THREAD

**Issue by MarcosRZ** [DigitalMachinist/loopback-angular-ui-router#7]
I'm getting the message:

> Warning: Task "serve" not found.

when I run `grunt serve`. The app works fine with `node .` command. Maybe the gruntfile is not being generated properly?

Anyway, this is an awesome generator. Congrats!

**Comment by DigitalMachinist** [comment]
It looks like a flubbed my getting started guide!

The command you're looking for is:

```
grunt server
```

I'll have to update my README.md to account for that. Hope it helps!
